name: filetree
version: 0.0.1
maintainer: eyeinsky <eyeinsky9@gmail.com>
synopsis: Fine-grained handling of paths and filesystem trees
description: See README at <https://github.com/eyeinsky/filetree#readme>
license: MIT
github: eyeinsky/filetree
category: System

ghc-options: -Wall -Wno-name-shadowing

dependencies:
  - base <= 4.10.0.0
  - lens < 5
  - bytestring
  - containers
  - directory
  - mtl
  - text
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - System.Path
    - System.Path.Dir
    - System.Path.File
    - System.Path.IO
    - System.File
    - System.FSTree
    - System.FSTree.Core
    - System.FSTree.DSL

tests:
  spec:
    ghc-options: -Wno-all
    main: Main.hs
    source-dirs: test
    dependencies:
      - filetree
      - tasty
      - tasty-hunit
      - tasty-quickcheck

default-extensions:
  - Arrows
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - EmptyDataDecls
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
